# Generated by Django 5.2.1 on 2025-05-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='radario_widget_code',
            field=models.TextField(blank=True, help_text='Полный HTML-код виджета Radario', null=True, verbose_name='Код виджета Radario'),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_system',
            field=models.CharField(choices=[('DIRECT', 'Прямая ссылка'), ('TICKETSCLOUD', 'TicketsCloud'), ('RADARIO', 'Radario')], default='DIRECT', max_length=20, verbose_name='Система продажи билетов'),
        ),
        migrations.AddField(
            model_name='event',
            name='ticketscloud_event_id',
            field=models.CharField(blank=True, help_text='Например: 6821dfc8b521c11bd5e8e245', max_length=255, null=True, verbose_name='ID события TicketsCloud'),
        ),
        migrations.AddField(
            model_name='event',
            name='ticketscloud_token',
            field=models.CharField(blank=True, help_text='Например: eyJhbGciOiJIUzI1NiIsImlzcyI6...', max_length=255, null=True, verbose_name='Токен TicketsCloud'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_link',
            field=models.URLField(blank=True, help_text="Используется только при выборе типа 'Прямая ссылка'", max_length=255, null=True, verbose_name='Прямая ссылка на билеты'),
        ),
    ]
