# Generated by Django 5.2 on 2025-04-26 21:59

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover',
            field=models.ImageField(upload_to=events.models.Event._get_upload_path_for_cover, verbose_name='Обложка для страницы'),
        ),
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(upload_to=events.models.Event._get_upload_path_for_poster, verbose_name='Обложка для карточки'),
        ),
    ]
