# Generated by Django 5.2.1 on 2025-05-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_radario_widget_code_event_ticket_system_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='radario_widget_code',
        ),
        migrations.AddField(
            model_name='event',
            name='radario_key',
            field=models.CharField(blank=True, help_text='Например: 01106bb07f3b726a899dd2ac93300217cd13d573f6f57', max_length=255, null=True, verbose_name='Ключ Radario'),
        ),
        migrations.AddField(
            model_name='event',
            name='radario_params',
            field=models.JSONField(blank=True, default=dict, help_text='Дополнительные параметры виджета в формате JSON', null=True, verbose_name='Параметры виджета Radario'),
        ),
    ]
