# Generated by Django 5.2 on 2025-04-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_cover_alter_event_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_active',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('ACTIVE', 'Активно'), ('STOP', 'Приостановлено'), ('CANCEL', 'Отменено')], default='DRAFT', max_length=10, verbose_name='Статус'),
        ),
    ]
