# Generated by Django 5.2.1 on 2025-05-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_radario_widget_code_event_radario_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='radario_params',
        ),
        migrations.AlterField(
            model_name='event',
            name='radario_key',
            field=models.CharField(blank=True, help_text='ID события из личного кабинета Radario', max_length=255, null=True, verbose_name='ID события Radario'),
        ),
    ]
