# Generated by Django 5.2 on 2025-04-30 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_is_active_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='age_restriction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='events.agerestriction', verbose_name='Возрастное ограничение'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='events.eventtype', verbose_name='Тип мероприятия'),
        ),
    ]
