# Generated by Django 5.2.1 on 2025-05-14 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_radario_params_alter_event_radario_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='radario_key',
            field=models.CharField(blank=True, help_text='Введите только цифровой ID события (например: 123456)', max_length=255, null=True, verbose_name='ID события Radario'),
        ),
        migrations.CreateModel(
            name='EventPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Поддерживается HTML разметка', verbose_name='Содержимое пуша')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='push', to='events.event')),
            ],
            options={
                'verbose_name': 'Пуш мероприятия',
                'verbose_name_plural': 'Пуши мероприятий',
            },
        ),
    ]
