# Generated by Django 5.2.1 on 2025-05-14 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_radario_key_eventpush'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAdvertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно')),
                ('token', models.CharField(max_length=100, verbose_name='ERID токен')),
                ('advertiser_name', models.CharField(max_length=255, verbose_name='Наименование рекламодателя')),
                ('advertiser_inn', models.CharField(max_length=12, verbose_name='ИНН рекламодателя')),
                ('additional_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advertising', to='events.event')),
            ],
            options={
                'verbose_name': 'Рекламная информация',
                'verbose_name_plural': 'Рекламная информация',
            },
        ),
    ]
