# Generated by Django 5.2.1 on 2025-05-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventadvertising'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventadvertising',
            name='advertiser_ogrn',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ОГРН рекламодателя'),
        ),
    ]
