# Generated by Django 5.2 on 2025-04-26 21:59

import tours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='cover',
            field=models.ImageField(upload_to=tours.models.Tour._get_upload_path_for_cover, verbose_name='Обложка для страницы'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='poster',
            field=models.ImageField(upload_to=tours.models.Tour._get_upload_path_for_poster, verbose_name='Обложка для карточки'),
        ),
    ]
